/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 67790202afd1c48526181cb1d04c1955)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat" | "ProjectManager" | "BuildRunner";
	}
	interface Env {
		SESSIONS: KVNamespace;
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		ProjectManager: DurableObjectNamespace<import("./src/server").ProjectManager>;
		BuildRunner: DurableObjectNamespace<import("./src/server").BuildRunner>;
		FILES: R2Bucket;
		DB: D1Database;
		VECTORIZE: VectorizeIndex;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
